name: Build Project

on:
  push:
    branches:
      - stable
      - dev
  pull_request:
    branches:
      - stable
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEVELOPMENT: ${{ github.ref_name == 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant permissions
        run: chmod +x ./gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build

      - name: Prepare artifact name
        id: artifact_name
        run: |
          REF_NAME="${{ github.head_ref || github.ref_name }}"
          SAFE_REF_NAME="${REF_NAME//\//-}"
          echo "name=lumi-$SAFE_REF_NAME" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lumi-${{ github.ref_name }}
          path: '**/build/libs/*.jar'